### PR TITLE
Update drust.pug

### PR DESCRIPTION
**Pull request by Fallett**
haha

### CODE REVIEW

**Comment by emilhem** [comment]
Wat

Fallet =? Hacked

**Comment by Vigren** [comment]
fallet == rude

**Comment by Kirens** [comment]
Think @bryal might be able to explain some of it.

**Comment by Fallett** [comment]
!(fallet == rude)
fallet == hacked

**Comment by bryal** [comment]
Yes, was me när vi kollade på sidan, no hax

**Pull request merged**
